### ISSUE TITLE
0.2.0

### ISSUE THREAD

**Issue by oscartbeaumont** [oscartbeaumont/rspc#106]
Breaking Changes:
 - [x] #94 - The current custom one is just wrong sometimes
 - [x] Fix TS `subscription` type (`[, null]` issue)
 - [x] Move Typescript tests to Vitest + add one for query, subscriptions & mutation for `never` or single item or many items in enum
 - [ ] New transport system
     - [x] Client v2
     - [ ] Execute chain of links correctly
     - [ ] Require a "terminatingLink" to expose a `map` and handler functions which are exposed to all links in the chain through a tRPC `runtime` style thing but extracted from the last link. Error if last link is not a terminatingLink.
     - [ ] Websocket Transport
     - [ ] Tauri Transport
     - [ ] Working `AbortController` on vanilla client and RQ
     - [ ] Both the vanilla client and hooks should have an optional global `onError` callback
     - [ ] Upgrade `@rspc/react`
     - [ ] Upgrade `@rspc/solid`
     - [x] HTTP Transport.
         - [x] Support for [this](https://trpc.io/docs/cors) for setting CORS, cookies and other fetch params.
         - [ ] I think the children type is still wrong on the SolidJS hooks
     - [ ] Docs
 - [ ] Interop Client
     - [ ] Basic unit tests for it derived from the old docs
     - [ ] Interop Client
     - [ ] Interop transports `FetchTransport` & `TauriTransport`
     - [ ] Check against current npm releases `.d.ts` that we are matching up
     - [ ] Move all tRPC private types into a subexport
     - [ ] Fix `.subscription` types
     - [ ] Fix main examples to use the old syntax but include some examples with the new syntax
 - [x] Dropped support for Axum extractors
     - [x] Completely dropped support for any async-style extractors - Both because it's not currently needed and also it also means no `Box<dyn Future>`!
     - [x] New httpz powered cookie API - styled after tower-cookies API
     - [x] New httpz powered request API - styled after Axum API
     - ~~httpz cookie signing~~
     - ~~httpz cookie encryption~~
     - ~~Fix working with the cookiejar over websockets~~
     - [ ] API for using legacy Axum extractors to help with the migration process.
     - As a personal note the cookie handling in rspc will need to be rewritten to not internally suck but for the next idea this is fine.
 - ~~Inline types by default - #101~~
 - [x] Export Typescript types using `type`'s instead of `interface` - #83
 - [x] Typescript export use `;` as separator instead of `,` - My vscode autocorrects to this on save
 - [x] Report errors on duplicates in Specta type name. These would previously be "undefined behavior"
 - [x] rspc no longer supports bigints + Specta features for restricting bigints
 - [x] Specta + rspc comment exporting
 - [x] Drop Normi from the repo. It remains in a branch for reference and will probably come back at some point.
 - [x] Use `.nest` instead of `.route` to attach the endpoint. This is so we can handle URL prefixes in the router. Also change from `/rspc/:id` to `/rspc`.
 - [x] Drop `endpoint_with_prefix` in favor of httpz being better integrated with routers.
 - [x] Remove `TMeta` - This will mess with your generics
 - [x] Redone Specta attribute parser. Now will have nicer compiler errors.
 - [x] Dropped beta OpenAPI support because it's not ready enough for practical usage and shouldn't have been included in the last release.
 - [x] Multithreaded Tauri executor

Features:
 - [x] #104
 - [x] https://github.com/oscartbeaumont/rspc/commit/c2d022c1cdb0156727983c8a240bff242f815206
     - [ ] Docs for this change

Internal:

 - [x] Less `clone` calls which should help with performance/memory usage.
 - [x] Using Specta for internal type safety

Prerelease:
 - Release notes + upgrade guide
 - Upgrade Twidge to test everything
 - Prepare Specta for release
   - [x] ~~Feature gate~~ Remove new language extractors
   - [x] Fix test suite and check it passes with my new macro work
   - [ ] Decide how much of oscartbeaumont/specta#1 will be included.
 - [ ] Ensure rspc builds and still works in Cloudflare Workers

**Comment by dlight** [comment]
just linking the other 0.1.3 issue, #70

**Comment by oscartbeaumont** [comment]
@dlight I forgot I created that. This issue is becoming the definitive source of truth for the next version. This release was expected to come out 2-3 months ago (hence the old issue) but life got in the way and was unable to finish it. I suspect they will have a lot of overlap but I won't include anyone on #70 if it's not mentioned here. If there is anything from #70 you really need let me know and I can prioritise it.

**Comment by killpowa** [comment]
How would you feel about adding https://github.com/oscartbeaumont/rspc/issues/19 to 0.1.3? I feel like it's a must-have for any non trivial app
