### ISSUE TITLE
0.2.1

### ISSUE THREAD

**Issue by oscartbeaumont** [oscartbeaumont/rspc#123]
rspc client:
 - [ ] Make `loggerLink` work without observable system
 - [ ] Internal type safety from the fetch call out using Specta on the JSON RPC types.
 - [ ] Fix typesafety hole where you can use `.build` and a type mapping link which will cause problems.
 - [ ] Batch link -> Batches queries so we can do them in a single request to the transport.
 - [ ] Logger link for debugging
 - [ ] Split link
 - [ ] Redo examples
     - [ ] Remove Astro example from rspc - The naming is confusing
     - [ ] Add solid-start + rspc example
     - [ ] SSR support for Solid Start and Next.js
     - [ ] Finish WIP upgraded Next.js example with examples of server and client components in app directory
 - [ ] Deduplicate link for server-to-server communication - docs should say it shouldn't be used with RQ
 - [ ] Retry link for server-to-server communication - docs should say it shouldn't be used with RQ
 - [ ] Allow delaying initialisation of websocket to first connection -> Good for Mattrax's auth flow
 - [ ] Fix Tauri transport issues:
     - [ ] Bug fixes
     - [ ] Retry on duplicate subscription id
     - [ ] SolidJS hook createSubscription createEffect returning function 💀 
     - [ ] Scoping websocket connection ID per JS "session"

rspc Rust:
 - [ ] Finish httpz upgrades
    - [ ] httpz cookie signing
    - [ ] httpz cookie encryption
    - [ ] Fix working with the cookiejar over websockets
 - [ ] #107 - Mostly docs changes
 - [ ] New `handle_json_rpc` executor system - WIP
 - [ ] Configuration option for #81
    ```rust
   /// TODO: Come up with more logical names
    pub enum LoggingMode {
          Hidden,
          HiddenOnlyInProd,
          AlwaysOn
    }
    ```
 - [ ] New syntax?
      - [ ] Lazily build procedures - When merging routes, the global data store on the parent should be used on the child routers.
     - [ ] System for invalidating queries
 - [ ] #22 - Decide how many servers I wanna add before this release.
 - [ ] Typesafe error handling -> Using Specta to export error and use it on the frontend

Specta:
 - [ ] `#specta(export = false)` container attribute for `export` feature -> Use in rspc unit tests
 - [ ] Fix Duplicate Type name detection not working + unit test for it

Other:
 - [ ] Clean rspc issue tracker
 - [ ] Interactive examples
 - [ ] Finish newer style docs (#103) + upgrade content to reflect this new release + redo doc content to include interactive examples
 - [ ] Update `create-rspc-app` and make it the recommended solution on the docs

Future:
- [ ] Neovim/Lunarvim plugin with snippets
- [x] #55
