### ISSUE TITLE
0.1.4

### ISSUE THREAD

**Issue by oscartbeaumont** [oscartbeaumont/rspc#160]
- [x] Refactor middleware system - #153
 - [x] Fix up Git branches `0.1.3` -> `main` and `main` -> `prev-main`
 - [x] Allow the executors to place nice with the `prev-main` Typescript to provide an easier migration path.
 - [ ] The middleware mapper API may be unsafe. If the `Output` doesn't eventually equal `T` then we get a runtime error.
 - [ ] Typesafe error handling using the `rspc::Error` trait
 - [ ] Allow changing the error type for a particular procedure???
 - [ ] https://github.com/spacedriveapp/spacedrive/pull/628
 - [ ] Migrate all Rust changes from `prev-main` into the alpha stuff or internals
 - [ ] Rename arg mapper to "middleware argument transformers"
 - [ ] Docs site:
      - [ ] Page with interactive example build using CodeSandbox
      - [ ] Document-supported Rust features
      - [ ] Authentication docs - Basic auth & Clerk example
      - [ ] Document new request + cookie APIs
      - [ ] Generate Typescript API docs -> https://github.com/shuding/nextra/issues/1380
      - [x] Select JS framework and have it auto-update all code samples + save preference
      - [x] Select JS package manager
      - [ ] Select Rust web framework and have it auto-update all code samples + save preference
      - [ ] When copying markdown links it should include query params for framework and package manager!
      - [ ] Document new middleware APIs + arg mapper
 - [ ] Update rspc vscode extension for new syntax
 - [ ] Proper Rust docs - https://docs.rs/rspc shouldn't be so empty!
 - [ ] Cleanup `alpha` module naming
 - [ ] Deprecate attributes put on everything ready
 - [ ] `AbortController`'s on the frontend
 - [ ] https://github.com/oscartbeaumont/rspc/issues/81
 - [ ] https://github.com/oscartbeaumont/rspc/issues/142
 - [ ] https://github.com/oscartbeaumont/rspc/issues/47
 - [x] https://github.com/oscartbeaumont/rspc/issues/131
 - [ ] https://github.com/oscartbeaumont/rspc/issues/135
 - [ ] httpz URL param passing worked out
 - [ ]  httpz Unit testing all platforms + rspc docs for them
 - [ ] Vercel Rust runtime + docs & example for using it
 - [ ]  https://github.com/oscartbeaumont/rspc/issues/145
 - [ ] [BLOCKED] Fix Tauri transport - https://github.com/oscartbeaumont/rspc/issues/141
 - [ ] Middleware functions should be able to be async or sync & return a value or result
 - [ ] Don't box the top layer. Eg. A procedure that doesn't use any async shouldn't be boxed or executable at all, it should just clone the value out of the HashMap (but still account for middleware)
 - [ ] Pre-poll future for the first value to see if it's `Ready<T>` or it's actually a future?

---

Changes:
 - Support for anyhow with `rspc::Error`. Must enabled the `anyhow` feature for this.
 - Remove `DoubleArgStreamMarker` and replace `StreamResolver` and  with `StreamRequestLayer` trait.
 - Drop `DoubleArgStreamMarker` type and `Resolver` trait. The bounds have been moved directly onto the `.query`/`.mutation`/`.subscription` methods. This was an artifact of a feature that was never implemented due to limitations in the Rust compiler's type inference capabilities.
 - `.subscription` now supports returning a `dyn Stream`, `Result<dyn Stream, rspc::Error>`, `dyn Future<Output = dyn Stream` and `dyn Future<Output = Result<dyn Stream, rspc::Error>>`.
 - Restrict names of procedures to prevent conflicts with internal procedures and invalid URLs.
 - Improve error for invalid names. Now uses `#[track_caller]` to provide a clickable path in the terminal to take you to error in your own code.
 - New JSON RPC executor
 - Cleanup Tauri subscriptions on page load -> This flows the behavior of a websocket.
 - Remove hack from previous Tauri IPC bug
 - impl RouterBuilderLike
 - Refactor `ProcedureDataType`. This is a breaking change but it's marked as an internal API
 - Added `typedef` to `RequestLayer` trait
