### ISSUE TITLE
Development Overview

### ISSUE THREAD

**Issue by oscartbeaumont** [oscartbeaumont/rspc#2]
Pre open-source:
 - [x] Website
 - [x] Basic Typescript runtime
 - [x] Do query & mutation over websocket
 - [x] Primitive Subscriptions working
 - [x] Publish Crate and NPM package
 - [x] Add npm link to sidebar on website

Spacedrive Features:
 - [x] Rename `CompiledRouter` to `Router` and `Router` to `RouterBuilder` + Give `CompiledRouter` a set of default generics
 - [x] `selection!(x, { field_one, field_two })` macro
 - [x] `selection!` macro on lists
 - [x] [Error Handling](https://trpc.io/docs/error-handling)
 - [x] Provide ctx function access to context/session/data/extensions + Alllow it to capture data
 - [x] #5 
 - [x] Subscriptions
    - [x] Access Context
    - [x] Export type definitions
    - [x] Subscription start/stop
 - [x] Subscriptions working with middleware
 - [x] React-query support
 - [x] Tauri bindings
 - [x] ~~Handling tenants or libraries. I am thinking maybe the ID comes from the request context but how would the frontend inject context. Maybe something on client but that has React context???~~
 - [x] Remove `trpc` compatibility to clean up code + typescript support for error handling
 - [x] Mattrax bindings are not generating correctly! This is #6

Fixes:
 - [x] Axum extrators are broken
 - [x] Allow resolver returning `&'static str` I think it needs a `ts_rs::TS` impl
 - [x] Fix all Rust warnings
 - [x] #3

**Comment by oscartbeaumont** [comment]
This weekend:
 - [ ] Finish `httpz` open source it + move rspc over to it -> Fixes #22 
 - [ ] Axum dynamic number of extractor -> Using a `macro_rules!` to generate the impls
 - [ ] Catch panics in resolvers and correctly return an error instead of terminating the HTTP connection.
 - [ ] Handling `Config` defined on a subrouter when merging. Warning when mounting multiple `Config`'s.
 - [ ] Split `exec()` to `exec_stream()` and exec_request()` or something
 - [ ] Redo the Typescript monorepo. Jump to definition working, Split Tauri and React out of base client.
 - [ ] CI/CD -> Clippy, Run Tests, Do Release
 - [ ] #23
 - [ ] #17
 - [ ] Rust documentation
 - [ ] #9 - This will be sick if I can make it work well!
 - [ ] Investigate JSON RPC compatibility?

Future:
 - [ ] #4 
 - [ ] Invalidate query + make it typesafe! #19
 - [ ] [Batch queries](https://trpc.io/docs/links)
 - [ ] Caching -> Done through cache control headers. Ensure this doesn't break batching!
 - [ ] [Route Meta](https://trpc.io/docs/metadata) #21
 - [ ] #18
 - [ ] `selection!` macro add abritary values Eg. `selection!(user, { __type: "user", name, email });` - This would be cool but may not be possible
 - [ ] `selection!` macro subselection Eg. `selection!(userWithPets, { name, email, pets: { name, email });`
 - [ ] Example with how to do pagination with Prisma Client Rust
 - [ ] Websocket heartbeat and kill stale connections
 - [ ] Allow application to detect if websocket connection is dropped -> This could be used for a visual warning.
 - [ ] Unit testing rspc crate
 - [ ] Passthrough Rust [deprecated](https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-deprecated-attribute) to [Typescript doc comment](https://stackoverflow.com/questions/60755711/is-it-possible-to-mark-something-as-deprecated-in-typescript)
 - [ ] Lightweight SolidJS client which can batch within renders - This is for Mattrax

Long Term:
 - [ ] Remove `tokio` from dependencies if possible
 - [ ] #7 
 - [ ] Investigate [watt](https://github.com/dtolnay/watt)?? or moving off `syn`. This probably won't be easy!
 - [ ] Rust client for doing microservices

**Comment by oscartbeaumont** [comment]
v0.0.5:
 - [x] Redo the Typescript monorepo. Jump to definition working, Split Tauri and React out of base client.
 - [x] Split up all Typescript packages 
 - [x] New syntax for defining plugins
 - [x] Plugin architecture
 - [x] Migrate to httpz -> Fixes #22
 - [x] #17
 - [x] Move example to Astro so it can use microfrontends
 - [ ] Open source httpz
 - [ ] Handling `Config` defined on a subrouter when merging. Warning when mounting multiple `Config`'s.
 - [ ] Split `exec()` to `exec_stream()` and exec_request()` or something
 - [ ] Catch panics in resolvers and correctly return an error instead of terminating the HTTP connection.
 - [ ] sqlx types in Specta
 - [ ] Rust documentation for docs.rs
 - [ ] Docs for beginners -> Using `Arc` + `Mutex` to get state into rspc. Contrast with Axum and Actix-web approaches to state.
 - [ ] Contributing guide, PR and Issue template
 - [ ] GitHub Social Banner + OpenGraph tags on documentation website
 - [ ] Using AbortController in React to prevent fetching once the component unrendered
 - [ ] CI/CD -> Clippy, Run Tests, Do Release, Dependabot

**Comment by oscartbeaumont** [comment]
v0.0.6:
 - [ ] #23
 - [ ] #21
 - [ ] #4 
 - [ ] #19
 - [ ] #18 
 - [ ] Investigate JSON RPC compatibility?
 - [ ] #9 
 - [ ] Caching -> Done through cache control headers. Ensure this doesn't break batching!
 - [ ] [Batch queries](https://trpc.io/docs/links)
 - [ ] Prevent needing to box middleware closure using trait with multiple associated types

**Comment by oscartbeaumont** [comment]
Document using a Cargo Alias to run the unit test

**Comment by oscartbeaumont** [comment]
Next release plans:
 - [ ] Batching
 - [ ] AbortController
 - [ ] #47 
 - [ ] #29

**Comment by oscartbeaumont** [comment]
Documentation Site v3 Upgrades:
 - [ ] Landing page to show off the tech and it's advantages
 - [ ] Jump to content thing for accesibility
 - [ ] Interactive demos -> Idk how but make it happen (Rust compiler on Netlify Functions would be wack).

**Comment by oscartbeaumont** [comment]
- [ ] Generic middleware response type
- [ ] Middleware func takes in `impl Serialize + Type`
- [ ] Build `impl GenericRouter` to fix the Spacedrive problem of returning routers

**Comment by oscartbeaumont** [comment]
- [ ] rspc.useInfiniteQuery
 - [ ] rspc.invalidateQuery
